services:
  - type: web
    name: soul-script
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_AI_API_KEY
        sync: false
      - key: REDIS_URL
        sync: false
      - key: NEXT_PUBLIC_APP_URL
        sync: false

  - type: redis
    name: soul-script-redis
    ipAllowList: []
    plan: free 